### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ragboyjr** [krakphp/lava#57]
This is a roadmap of features that I hope to build and have in the coming lava versions.

- [ ] Testing Utilities
  - [ ] Ability for easy integration testing
  - [ ] Ability to create plugins for different testing libraries
  - [ ] Should be easy to integrate with any framework
- [ ] App Caching/Flushing/Warming
  - [ ] Ability to cache app containers for lazy evaluation
  - [ ] Ability to cache app containers for non auto-wireing
- [ ] Easy Database integration
- [ ] Easy session usage
- [ ] Easy frontend integration
- [ ] Easy separation of routes
- [ ] Agnostic Templating
  - [ ] Support Twig, Plates
  - [ ] Create a template context that would share among different engines
- [ ] Easy response modeling
- [ ] Unified error handling via exceptions
- [ ] Logging out of the box
- [ ] Easy cache integration
- [ ] Unified Bootstrapping
  - [ ] Bundle bootstrapping make events for when should fire
- [ ] Normalize packages vs service providers
- [ ] Easy validation
  - [ ] should handle api and frontend
- [ ] Easy request interface
- [ ] App Request Context
- [ ] Configuration Management
  - [ ] Ability to lazy load config files. Maybe support multiple formats with ability to cache the config files
- [ ] Asset Management
  - [ ] Bundle assets
  - [ ] Integrate with webpack
  - [ ] Integrate with CDN
- [ ] Queued Jobs
- [ ] Scheduled Jobs
- [ ] Console Commands
- [ ] Everything should be easily composable and removable. If you want to only make a console app, you can, no need to include http stuff.
